### ISSUE TITLE
Turing Machine RS must be calmed

### ISSUE THREAD

**Issue by helltraitor** [Helltraitor/turing-machine-rs#2]
## Problem
Turing Machine RS can `panic!` for some reasons (e.g. default symbol of the classic machine is not in the program alphabet).

## Motivation
Turing Machine RS could panic and that may not be acceptable for users. Also, panic (when unnecessary) is not the best way to develop software. Instead, the good idea is to use `Option` and `Result` types.

## Solution
'Calm down' this crate by following these steps:
- Create a new branch (e.g. `Calm`).
- Use `Result` type for `Classic::new` and `Configuration::new` (`new_nrm`, `new_std`) methods.
- Remove check creation for `Program`. Use the `Program::insert` method (see below) for checks instead.
- Replace returning types in Turing Machine trait by `Result` type with the error enumeration `ExecutionError` (probalby add `NoTailFor(Head)` and `InfinityFor(Head)` variants).
- Replace `Program::set` method by `Program::insert` method with `Result` returning type (probably `&str + 'static` type depends on possible realization problems).
- Replace `Program::extend` by `Program::with`.

Other constraints (`Result` output type for `With` trait) will almost certainly be implemented.

## Useful sources
[The Rust Programming Language: Error Handling](https://doc.rust-lang.org/book/ch09-00-error-handling.html)

**Comment by helltraitor** [comment]
## TODO list
- [x] Created a new branch `calm`.
- [x] Used Result type for `Classic::new`.
- [x] Used Result type for `Configuration::new` (new_nrm, new_std) methods.
- [x] Used Result type fot `Program::get`, `Program::set`.
- [x] Replaced `Program::extend` by `With::with` and Result type.
- [x] Used Result type for `TuringMachine` trait.
- [x] Updated documents.
- [x] Refactored Tests (tests are always updating within the api updates).
